# Generated by Django 4.2.4 on 2025-08-13 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='originals/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('bg_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('is_transparent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
